name: 🦋 Changesets Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 🦋 Changesets Release
    runs-on: ubuntu-latest
    if: |
      github.repository == 'supabase-community/supabase-management-js'
    outputs:
      published_packages: ${{ steps.changesets.outputs.publishedPackages }}
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"

      - name: 📥 Download deps
        run: npm install

      - name: 🔎 Type check
        run: npm run typecheck

      - name: 🔐 Setup npm auth
        run: |
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

        # This action has two responsibilities. The first time the workflow runs
        # (initial push to the `main` branch) it will create a new branch and
        # then open a PR with the related changes for the new version. After the
        # PR is merged, the workflow will run again and this action will build +
        # publish to npm.
      - name: 🚀 PR / Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run changeset:version
          commit: "chore: Update version for release"
          title: "chore: Update version for release"
          publish: npm run changeset:release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
